---
# tasks file for leaf-init-j2

- name: Generate Leaf config
  ansible.builtin.template:
    src: leaf.j2
    dest: roles/leaf-init-j2/files/{{ inventory_hostname }}.cfg
    mode: '0644'

- name: Push Leaf config
  cisco.nxos.nxos_config:
    src: roles/leaf-init-j2/files/{{ inventory_hostname }}.cfg
    provider: "{{ nxos_provider }}"
    save_when: changed
...
